version: '3.8'

services:
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - '3000:3000'
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
